services:
  - type: web
    name: orbidigi-scraper-name
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: EVERBEE_EMAIL
        value: leticiaterranegra@hotmail.com
      - key: EVERBEE_PASS
        value: g4DwW6W.XKSsdgR
